#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=60
STOP=15

start() {
        echo launch apache
        # commands to launch application
        apachectl start
}

restart() {
        echo re-start apache
        # commands to launch application
        apachectl restart
}

stop() {
        echo stop apache
        # commands to kill application
        apachectl stop
}
